In [1]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="@brent31560733",
    database="ecommerce_10k"
)

print("Connection successful!")

Connection successful!

In [2]:
def run_query(sql):
    return pd.read_sql(sql, conn)

In [3]:
tables= run_query("""
SHOW tables
""")
tables

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

  Tables_in_ecommerce_10k
0               customers
1     marketing_campaigns
2             order_items
3                  orders
4                payments
5                products
6                 reviews
7                shipping

1. Find all customers from Kenya

In [4]:
kenya_customers=run_query("""
SELECT * FROM customers
WHERE country = 'Kenya'
limit 10;                                               
                          """)
kenya_customers

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

   customer_id full_name  gender            email country     city signup_date
0            1     User1  Female   user1@mail.com   Kenya  Nairobi  2025-01-29
1            6     User6    Male   user6@mail.com   Kenya  Mombasa  2023-08-27
2           10    User10    Male  user10@mail.com   Kenya  Mombasa  2024-12-15
3           16    User16    Male  user16@mail.com   Kenya   Nakuru  2024-07-03
4           17    User17  Female  user17@mail.com   Kenya   Nakuru  2023-03-22
5           31    User31  Female  user31@mail.com   Kenya   Kisumu  2024-02-15
6           41    User41  Female  user41@mail.com   Kenya  Nairobi  2023-06-06
7           43    User43  Female  user43@mail.com   Kenya   Nakuru  2024-01-26
8           46    User46    Male  user46@mail.com   Kenya   Kisumu  2025-02-26
9           49    User49  Female  user49@mail.com   Kenya   Kisumu  2024-05-27

2. Count total orders

In [5]:
count_total_orders=run_query("""
select COUNT(*) 
as total_orders 
from orders;                             """)
count_total_orders

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

   total_orders
0         10000

3. Find all cancelled orders

In [6]:
cancelled_orders=run_query("""
select * from orders
where status='Cancelled';                           """)
cancelled_orders

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

      order_id  customer_id  order_date     status
0            3          229  2023-12-04  Cancelled
1            5          335  2024-12-10  Cancelled
2            9          258  2024-12-07  Cancelled
3           10           61  2024-01-12  Cancelled
4           14          311  2024-03-01  Cancelled
...        ...          ...         ...        ...
2465      9990           17  2023-03-23  Cancelled
2466      9992           57  2023-12-17  Cancelled
2467      9994           56  2024-07-01  Cancelled
2468      9995          174  2024-04-14  Cancelled
2469      9999           84  2023-06-18  Cancelled

[2470 rows x 4 columns]

4. Show products costing above $500

In [7]:
product500=run_query("""
select * from products
where price > 500                     
order by price desc
                                       ;""")
product500

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

     product_id product_name     category   brand    cost    price
0           185   Product185      Fashion  Adidas  868.42  1379.88
1           113   Product113       Sports  Adidas  899.64  1312.97
2            60    Product60         Home    Sony  838.44  1274.08
3            22    Product22  Electronics  Adidas  859.27  1262.66
4           115   Product115       Beauty  Adidas  875.42  1244.12
..          ...          ...          ...     ...     ...      ...
122          46    Product46      Fashion  Adidas  399.53   521.56
123         100   Product100      Fashion   Apple  364.25   518.98
124          36    Product36      Fashion    Dell  345.24   516.42
125         152   Product152      Fashion    Dell  455.07   510.89
126           4     Product4       Beauty    Nike  392.06   510.55

[127 rows x 6 columns]

5. Find customers who signed up in 2024

In [8]:
customers_2024=run_query("""
select * from customers
where year(signup_date)=2024;                         """)
customers_2024

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

,customer_id,full_name,gender,email,country,city,signup_date
0,3,User3,Female,user3@mail.com,Uganda,Kampala,2024-11-23
1,4,User4,Male,user4@mail.com,South Africa,Johannesburg,2024-08-27
2,7,User7,Female,user7@mail.com,South Africa,Johannesburg,2024-07-28
3,10,User10,Male,user10@mail.com,Kenya,Mombasa,2024-12-15
4,14,User14,Male,user14@mail.com,Nigeria,Lagos,2024-01-03
...,...,...,...,...,...,...,...
210,487,User487,Female,user487@mail.com,Kenya,Kisumu,2024-03-29
211,488,User488,Male,user488@mail.com,Nigeria,Abuja,2024-09-13
212,492,User492,Male,user492@mail.com,South Africa,Cape Town,2024-06-23
213,498,User498,Male,user498@mail.com,Kenya,Nairobi,2024-05-24
214,500,User500,Male,user500@mail.com,Nigeria,Ibadan,2024-12-21

6. Show customer names with their orders

In [9]:
customers_names=run_query("""
SELECT 
    o.order_id,
    c.full_name,
    o.order_date,
    o.status
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id;                          """)
customers_names

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

      order_id full_name  order_date     status
0            1   User480  2023-01-07    Shipped
1            2   User134  2023-08-30    Pending
2            3   User229  2023-12-04  Cancelled
3            4   User155  2023-09-25  Delivered
4            5   User335  2024-12-10  Cancelled
...        ...       ...         ...        ...
9995      9996   User145  2024-01-29  Delivered
9996      9997    User90  2024-07-30    Pending
9997      9998   User415  2023-01-16    Pending
9998      9999    User84  2023-06-18  Cancelled
9999     10000   User189  2023-03-04    Pending

[10000 rows x 4 columns]

7. Calculate total revenue

In [10]:
total_revenue=run_query("""
select sum(amount) as total_revenue from payments;                        """)
total_revenue

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

   total_revenue
0     9639114.34

8. Revenue generated per country

In [11]:
revenue_per_country=run_query("""
SELECT 
    c.country,
    SUM(p.amount) AS revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.country
ORDER BY revenue DESC;                            """)
revenue_per_country

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

        country     revenue
0       Nigeria  2197291.15
1      Tanzania  1942066.85
2        Uganda  1935863.91
3  South Africa  1853984.91
4         Kenya  1709907.52

9. Top 10 highest spending customers

In [12]:
top_10_spending=run_query("""
SELECT 
    c.full_name,
    c.country,
    c.gender,
    c.city,
    o.customer_id,
    p.order_id,
    SUM(p.amount) AS total_spent
FROM ecommerce_10k.customers AS c
JOIN ecommerce_10k.orders AS o
ON c.customer_id = o.customer_id
JOIN ecommerce_10k.payments AS p
ON p.order_id = o.order_id
GROUP BY 
    c.full_name,
    c.country,
    c.gender,
    c.city,
    o.customer_id,
    p.order_id
ORDER BY total_spent DESC
LIMIT 10;
                          """)
top_10_spending

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

,full_name,country,gender,city,customer_id,order_id,total_spent
0,User376,Uganda,Male,Entebbe,376,1433,1999.66
1,User61,Tanzania,Female,Arusha,61,3503,1999.31
2,User344,South Africa,Male,Cape Town,344,735,1999.15
3,User134,Uganda,Male,Kampala,134,4862,1998.96
4,User178,Nigeria,Male,Ibadan,178,3235,1998.89
5,User247,Kenya,Female,Kisumu,247,3444,1998.78
6,User449,Kenya,Female,Nakuru,449,9847,1998.63
7,User228,Tanzania,Male,Arusha,228,1163,1998.54
8,User87,Nigeria,Female,Abuja,87,6911,1998.48
9,User37,South Africa,Female,Cape Town,37,1614,1998.41

11. Customers who never placed an order

In [13]:
customers_with_no_order=run_query("""
SELECT c.*
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;                                  """)
customers_with_no_order

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

Empty DataFrame
Columns: [customer_id, full_name, gender, email, country, city, signup_date]
Index: []

12. Orders without payments

In [14]:
unpaid_orders=run_query("""
select o.order_id, o.status,p.amount from ecommerce_10k.orders
as o
join ecommerce_10k.payments as p
on o.order_id=p.order_id
where amount = 0;
                        """)
unpaid_orders

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

Empty DataFrame
Columns: [order_id, status, amount]
Index: []

13. Average order value

In [15]:
average_order_value=run_query("""
select avg(amount) as average_order_value from ecommerce_10k.payments;      """)
average_order_value

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

   average_order_value
0          1010.707176

14. Profit generated per product

In [16]:
profit_per_product=run_query("""
SELECT 
    p.brand,
    SUM(p.price) - SUM(p.cost) AS total_profit
FROM ecommerce_10k.products AS p
JOIN ecommerce_10k.order_items AS oi
ON oi.product_id = p.product_id
JOIN ecommerce_10k.payments AS pa
ON pa.order_id = oi.order_id
GROUP BY p.brand;""")
profit_per_product

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

     brand  total_profit
0    Apple     365567.79
1   Adidas     446687.10
2     Sony     325672.72
3     Dell     344464.77
4       HP     338396.39
5     Nike     454389.50
6  Samsung     404270.42

15. Customers spending above average

In [17]:
spending_above_average=run_query("""
SELECT 
    t.customer_id,
    t.full_name,
    t.total_spent
FROM (
    SELECT 
        c.customer_id,
        c.full_name,
        SUM(p.amount) AS total_spent
    FROM ecommerce_10k.customers c
    JOIN ecommerce_10k.orders o
    ON c.customer_id = o.customer_id
    JOIN ecommerce_10k.payments p
    ON o.order_id = p.order_id
    GROUP BY c.customer_id, c.full_name
) t
WHERE t.total_spent > (
    SELECT AVG(order_total)
    FROM (
        SELECT SUM(amount) AS order_total
        FROM ecommerce_10k.payments
        GROUP BY order_id
    ) x
);                                 """)
spending_above_average

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

     customer_id full_name  total_spent
0            480   User480     19979.90
1            134   User134     28710.69
2            229   User229     21586.25
3            155   User155     18980.19
4            335   User335     23287.24
..           ...       ...          ...
495          450   User450      7660.56
496          326   User326     15916.03
497          484   User484     22404.83
498          464   User464     19760.64
499          271   User271     18164.06

[500 rows x 3 columns]

16. Find products with above-average prices

In [18]:
above_average_products=run_query("""
SELECT *
FROM products
WHERE price > (
    SELECT AVG(price)
    FROM products
);                                 """)
above_average_products

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

    product_id product_name     category    brand    cost    price
0            6     Product6         Home    Apple  723.18  1019.01
1           11    Product11      Fashion  Samsung  816.27  1040.49
2           14    Product14       Beauty     Sony  856.65  1211.28
3           15    Product15       Sports     Dell  511.72   711.15
4           16    Product16         Home  Samsung  575.42   812.64
..         ...          ...          ...      ...     ...      ...
93         189   Product189  Electronics  Samsung  520.98   712.48
94         194   Product194       Sports   Adidas  449.58   705.52
95         196   Product196      Fashion    Apple  660.70   940.93
96         197   Product197       Sports     Dell  665.59   995.31
97         198   Product198       Beauty     Sony  683.98   812.40

[98 rows x 6 columns]

17. Rank customers by spending- use windows function

In [19]:
spending_rank=run_query("""
SELECT 
    c.customer_id,
    c.full_name,
    SUM(p.amount) AS total_spent,
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS spending_rank
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_id, c.full_name;                        """)
spending_rank

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

     customer_id full_name  total_spent  spending_rank
0            437   User437     33839.02              1
1             50    User50     31909.82              2
2              6     User6     31763.64              3
3            236   User236     31680.02              4
4            422   User422     31585.95              5
..           ...       ...          ...            ...
495          214   User214      7912.32            496
496          213   User213      7792.87            497
497          450   User450      7660.56            498
498           36    User36      7039.26            499
499          260   User260      5906.86            500

[500 rows x 4 columns]

18. Running total of revenue over time

In [20]:
total_revenue_over_time=run_query("""
SELECT 
    payment_date,
    amount,
    SUM(amount) OVER (
        ORDER BY payment_date
    ) AS running_revenue
FROM payments;                                """)
total_revenue_over_time

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

     payment_date   amount  running_revenue
0      2023-01-01  1928.55          3279.56
1      2023-01-01   185.01          3279.56
2      2023-01-01  1000.37          3279.56
3      2023-01-01   165.63          3279.56
4      2023-01-02   237.18         13823.91
...           ...      ...              ...
9532   2025-05-01   508.89       9639114.34
9533   2025-05-01    40.63       9639114.34
9534   2025-05-01    53.39       9639114.34
9535   2025-05-01  1685.61       9639114.34
9536   2025-05-01   807.21       9639114.34

[9537 rows x 3 columns]

19. Previous order date per customer

In [21]:
previous_order_date=run_query("""
SELECT 
    customer_id,
    order_date,
    LAG(order_date) OVER (
        PARTITION BY customer_id
        ORDER BY order_date
    ) AS previous_order_date
FROM orders;                             """)
previous_order_date

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

      customer_id  order_date previous_order_date
0               1  2023-01-05                None
1               1  2023-01-25          2023-01-05
2               1  2023-01-25          2023-01-25
3               1  2023-04-05          2023-01-25
4               1  2023-06-17          2023-04-05
...           ...         ...                 ...
9995          500  2024-10-23          2024-09-27
9996          500  2024-10-29          2024-10-23
9997          500  2024-12-14          2024-10-29
9998          500  2024-12-16          2024-12-14
9999          500  2025-04-29          2024-12-16

[10000 rows x 3 columns]

20. Monthly revenue trend + growth rate

In [22]:
monthly_revenue=run_query("""
SELECT 
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue,
    ROUND(
        (
            revenue - LAG(revenue) OVER (ORDER BY month)
        )
        /
        LAG(revenue) OVER (ORDER BY month) * 100,
        2
    ) AS growth_rate_percentage
FROM (
    SELECT 
        DATE_FORMAT(payment_date, '%Y-%m') AS month,
        SUM(amount) AS revenue
    FROM payments
    GROUP BY month
) t;                          """)
monthly_revenue

C:\Users\hp\AppData\Local\Temp\ipykernel_7552\849332196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

      month    revenue  previous_month_revenue  growth_rate_percentage
0   2023-01  340832.14                     NaN                     NaN
1   2023-02  352982.56               340832.14                    3.56
2   2023-03  374160.00               352982.56                    6.00
3   2023-04  322562.26               374160.00                  -13.79
4   2023-05  360002.80               322562.26                   11.61
5   2023-06  338477.01               360002.80                   -5.98
6   2023-07  342429.23               338477.01                    1.17
7   2023-08  366391.02               342429.23                    7.00
8   2023-09  312552.65               366391.02                  -14.69
9   2023-10  352268.31               312552.65                   12.71
10  2023-11  304546.96               352268.31                  -13.55
11  2023-12  309749.42               304546.96                    1.71
12  2024-01  372203.08               309749.42                   20.16
13  2024-02  339151.11               372203.08                   -8.88
14  2024-03  329080.40               339151.11                   -2.97
15  2024-04  327473.99               329080.40                   -0.49
16  2024-05  383063.13               327473.99                   16.98
17  2024-06  352888.60               383063.13                   -7.88
18  2024-07  349981.15               352888.60                   -0.82
19  2024-08  355046.05               349981.15                    1.45
20  2024-09  326129.37               355046.05                   -8.14
21  2024-10  368901.85               326129.37                   13.12
22  2024-11  321840.87               368901.85                  -12.76
23  2024-12  393221.80               321840.87                   22.18
24  2025-01  334294.01               393221.80                  -14.99
25  2025-02  317493.69               334294.01                   -5.03
26  2025-03  350691.56               317493.69                   10.46
27  2025-04  331597.54               350691.56                   -5.44
28  2025-05    9101.78               331597.54                  -97.26